/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        "on-primary":               "#e2e2e2",
        "surface-container":        "#eeeeee",
        "surface-container-highest":"#e2e2e2",
        "on-background":            "#1a1c1c",
        "on-surface":               "#1a1c1c",
        "surface":                  "#f9f9f9",
        "surface-container-high":   "#e8e8e8",
        "primary-container":        "#3b3b3b",
        "surface-container-low":    "#f3f3f4",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container":   "#1b1b1b",
        "on-surface-variant":       "#474747",
        "outline-variant":          "#c6c6c6",
        "secondary-container":      "#d4d4d4",
        "primary":                  "#000000",
        "surface-tint":             "#5e5e5e",
        "secondary":                "#5e5e5e",
        "surface-variant":          "#e2e2e2",
        "primary-fixed":            "#5e5e5e",
        "tertiary":                 "#3a3c3c",
        "inverse-primary":          "#c6c6c6",
        "outline":                  "#777777",
        "surface-dim":              "#dadada",
        "tertiary-container":       "#737575",
        "secondary-fixed":          "#c6c6c6",
        "background":               "#f9f9f9",
        "error":                    "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      fontFamily: {
        headline: ["'Work Sans'", "sans-serif"],
        body:     ["'Inter'",     "sans-serif"],
        label:    ["'Space Grotesk'", "sans-serif"],
      },
    },
  },
  plugins: [],
};
